# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "io.buildpacks.samples.hello-universe"
version = "0.0.1"
name = "Hello Universe Buildpack"

# Order used for detection
[[order]]
[[order.group]]
id = "io.buildpacks.samples.hello-world"
version = "0.0.1"

[[order.group]]
id = "io.buildpacks.samples.hello-moon"
version = "0.0.1"

[[order]]
[[order.group]]
id = "io.buildpacks.samples.hello-world"
version = "0.0.1"

[[order.group]]
id = "io.buildpacks.samples.ruby-bundler"
version = "0.0.1"

[[dependencies]]
id = "io.buildpacks.samples.hello-moon"
uri = "../hello-moon"

[[dependencies]]
id = "io.buildpacks.samples.hello-world"
uri = "../hello-world"

[[dependencies]]
id = "io.buildpacks.samples.ruby-bundler"
uri = "../ruby-bundler"
