[[buildpacks]]
id = "io.buildpacks.samples.java"
uri = "./java-buildpack"
latest = true

[[groups]]
buildpacks = [ { id = "io.buildpacks.samples.java", version = "latest" } ]

[stack]
id = "io.buildpacks.stacks.bionic"
run-image = "cnbs/run:latest"
build-image = "cnbs/build:latest"
