# Buildpacks to include in builder
[[buildpacks]]
id = "io.buildpacks.samples.java-maven"
version = "0.0.1"
uri = "../../buildpacks/java-maven"

[[buildpacks]]
id = "io.buildpacks.samples.kotlin-gradle"
version = "0.0.1"
uri = "../../buildpacks/kotlin-gradle"

[[buildpacks]]
image = "cnbs/sample-package:hello-universe"

# Order used for detection
[[order]]
[[order.group]]
id = "io.buildpacks.samples.java-maven"
version = "0.0.1"

[[order]]
[[order.group]]
id = "io.buildpacks.samples.kotlin-gradle"
version = "0.0.1"

[[order]]
[[order.group]]
id = "io.buildpacks.samples.hello-universe"
version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.samples.stacks.alpine"
run-image = "cnbs/sample-stack-run:alpine"
build-image = "cnbs/sample-stack-build:alpine"

[lifecycle]
uri = "file:///Users/pivotal/workspace/lifecycle/out/lifecycle-v0.5.0+linux.x86-64.tgz"
