# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "io.buildpacks.samples.ruby-bundler"
version = "0.0.1"
name = "Sample Ruby Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.bionic"
