# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "io.buildpacks.samples.ruby-bundler"
version = "0.0.1"
name = "Sample Ruby Buildpack"
homepage = "https://github.com/buildpacks/samples/tree/master/buildpacks/ruby-bundler"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.bionic"
