[[buildpacks]]
id = "io.buildpacks.samples.java"
version = "0.0.1"
uri = "../buildpacks/java-maven"

[[order]]
group = [ { id = "io.buildpacks.samples.java", version = "0.0.1" } ]

[stack]
id = "io.buildpacks.stacks.bionic"
run-image = "sample/stack-run:latest"
build-image = "sample/stack-build:latest"
