# Stack that will be used by the builder
[stack]
id = "io.buildpacks.samples.stacks.nanoserver-1809"
run-image = "cnbs/sample-stack-run:nanoserver-1809"
build-image = "cnbs/sample-stack-build:nanoserver-1809"
