# Buildpack API version
api = "0.2"

[buildpack]
  id = "io.buildpacks.samples.meta-world"
  name = "Metaworld buildpack"
  version = "0.0.1"

[[order]]
[[order.group]]
    id="io.buildpacks.samples.hello-world"
    version="0.0.1"

[[order.group]]
    id="io.buildpacks.samples.ruby-bundler"
    version="0.0.1"
