# Buildpacks to include in builder
[[buildpacks]]
id = "io.buildpacks.samples.java-maven"
version = "0.0.1"
uri = "../../buildpacks/java-maven"

[[buildpacks]]
id = "io.buildpacks.samples.kotlin-gradle"
version = "0.0.1"
uri = "../../buildpacks/kotlin-gradle"

[[buildpacks]]
id = "io.buildpacks.samples.ruby-bundler"
version = "0.0.1"
uri = "../../buildpacks/ruby-bundler"

[[buildpacks]]
id = "io.buildpacks.samples.ruby-bundler"
version = "0.0.2"
uri = "../../buildpacks/ruby-bundler-02"

[[buildpacks]]
id = "io.buildpacks.samples.hello-moon"
version = "0.0.1"
uri = "../../buildpacks/hello-moon"

[[buildpacks]]
id = "io.buildpacks.samples.hello-world"
version = "0.0.1"
uri = "../../buildpacks/hello-world"

[[buildpacks]]
id = "io.buildpacks.samples.meta-moon"
version = "0.0.1"
uri = "../../buildpacks/meta-buildpack-hello-moon"

[[buildpacks]]
id = "io.buildpacks.samples.meta-world"
version = "0.0.1"
uri = "../../buildpacks/meta-buildpack-hello-world"

# Order used for detection
[[order]]
[[order.group]]
id = "io.buildpacks.samples.java-maven"
version = "0.0.1"

[[order]]
[[order.group]]
id = "io.buildpacks.samples.kotlin-gradle"
version = "0.0.1"

[[order]]
[[order.group]]
id = "io.buildpacks.samples.ruby-bundler"
version = "0.0.1"

[[order]]
[[order.group]]
id = "io.buildpacks.samples.meta-moon"
version = "0.0.1"

[[order]]
[[order.group]]
id = "io.buildpacks.samples.meta-world"
version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.samples.stacks.bionic"
run-image = "cnbs/sample-stack-run:bionic"
build-image = "cnbs/sample-stack-build:bionic"
